[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"
  autoLaunch = true

# Important: Add these headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "interest-cohort=()"
    Access-Control-Allow-Origin = "https://career-survey.netlify.app"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Set-Cookie = """
      HttpOnly;
      Secure;
      SameSite=Lax;
      Path=/
    """
    Content-Security-Policy = """
      default-src 'self' https://*.netlify.app https://*.netlify.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.netlify.com;
      style-src 'self' 'unsafe-inline';
      connect-src 'self' https://*.netlify.app https://*.netlify.com;
      frame-src 'self' https://*.netlify.com;
      img-src 'self' data: https://*.netlify.com;
    """ 